//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_11_Compatibility_Checker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows_11_Compatibility_Checker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap circle_cropped__Custom___1_1 {
            get {
                object obj = ResourceManager.GetObject("circle-cropped (Custom) (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3015E
        ///3020E
        ///Athlon Gold 3150C
        ///Athlon Gold 3150U
        ///Athlon Silver 3050C
        ///Athlon Silver 3050e
        ///Athlon Silver 3050U
        ///Athlon 3000G
        ///Athlon 300GE
        ///Athlon 300U
        ///Athlon 320GE
        ///Athlon Gold 3150G
        ///Athlon Gold 3150GE
        ///Athlon Silver 3050GE
        ///EPYC 7232P
        ///EPYC 7252
        ///EPYC 7262
        ///EPYC 7272
        ///EPYC 7282
        ///EPYC 7302
        ///EPYC 7302P
        ///EPYC 7352
        ///EPYC 7402
        ///EPYC 7402P
        ///EPYC 7452
        ///EPYC 7502
        ///EPYC 7502P
        ///EPYC 7532
        ///EPYC 7542
        ///EPYC 7552
        ///EPYC 7642
        ///EPYC 7662
        ///EPYC 7702
        ///EPYC 7702P
        ///EPYC 7742
        ///EPYC 7F32
        ///EPYC 7F52
        ///EPYC 7F72
        ///EPYC 7H12
        ///E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPUs {
            get {
                return ResourceManager.GetString("CPUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap github__Custom_ {
            get {
                object obj = ResourceManager.GetObject("github (Custom)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap github_white__Custom_ {
            get {
                object obj = ResourceManager.GetObject("github_white__Custom_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap twitter__Custom_ {
            get {
                object obj = ResourceManager.GetObject("twitter (Custom)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap twitter_white__Custom_ {
            get {
                object obj = ResourceManager.GetObject("twitter_white__Custom_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Windows_11 {
            get {
                object obj = ResourceManager.GetObject("Windows 11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsCritical {
            get {
                object obj = ResourceManager.GetObject("WindowsCritical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsHelp__Custom_ {
            get {
                object obj = ResourceManager.GetObject("WindowsHelp (Custom)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsHelp__Custom_1 {
            get {
                object obj = ResourceManager.GetObject("WindowsHelp (Custom)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsSuccess {
            get {
                object obj = ResourceManager.GetObject("WindowsSuccess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsWarning {
            get {
                object obj = ResourceManager.GetObject("WindowsWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
